const quotes = [
    "No hay que ir para atrás ni para darse impulso <br>- Lao Tsé",
    "Haz el amor y no la guerra  <br> -John Lennon",
    "Las guerras seguirán mientras el color de la piel siga siendo más importante que el de los ojos <br>- Bob Marley",
    "Pensamos demasiado y sentimos muy poco <br>- El Gran Dictador",
    "No me acuerdo de olvidarte <br>- Memento",
    "Hablar es barato. Enséñame el código <br>- Linus Torvalds",
    "La abstracción es el principio de toda creación",
    "Un problema bien planteado, es un problema ya resuelto a la mitad",
    "Podrán quitarnos la vida, pero nunca podrán arrebatarnos la libertad <br>- Braveheart",
    "Lo llaman 'una Royale con Queso' <br>- Pulp Fiction",
    "¿De qué sirve confesarme si no me arrepiento? <br>- El Padrino 2",
    "Buenos días… y por si no volvemos a vernos: buenos días, buenas tardes y buenas noches <br>- El Show de Truman",
    "Esta noche cenaremos en el infierno <br>- 300",
    "La muerte nos sonríe a todos, devolvámosle la sonrisa <br>- El Gladiador",
    "Yo no estoy loco, mi realidad es diferente a la tuya <br>- Alicia en el país de las Maravillas",
    "Hay personas por las que vale la pena derretirse <br>- Frozen",
    "Los mejores pilotos están en la tierra <br>- Proverbio holandés",
    "La pobreza hace ladrones y el amor poetas  <br>- Proverbio chino",
    "Hay un susurro donde alguna vez hubo una tormenta <br>- The Rolling stones",
]